### PR TITLE
minor edits for clarity

### PR DESCRIPTION
**Pull request by tkellen**

### CODE REVIEW

**Comment by tkellen** [comment]
Any thoughts here?

**Comment by dgeb** [comment]
@tkellen sorry to delay - I was just waiting for a chance to talk with @wycats about allowing integer IDs (in addition to strings). If you want to remove that one change, I'd be glad to merge everything else. Or if you want to wait a day or two, I'll be getting his take on everything. Either way, thanks again for reviewing!

**Comment by tkellen** [comment]
Sure thing!  No rush, just saw you mention this to Konstantine earlier and it reminded me you hadn't replied.

**Comment by dgeb** [comment]
@tkellen thanks again for the review and edits. I'm merging this and will finesse your changes a bit as I put together this PR.

Yehuda and I talked about allowing integer IDs and decided against it because of the problems associated with tracking IDs of multiple types in an identity map (a lesson learned the hard way with ember-data).

**Comment by tkellen** [comment]
:+1:

**Pull request merged**
